server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    azure:
      storage:
        blob:
          container-name: luu-tru-tai-lieu
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/luu-tru-tai-lieu?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 3000
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 3600000
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 2MB
  mail:
    confirm-url: ${URL_EMAIL_CONFIRMATION:http://localhost:8080/api/v1/user/confirm} #url xac nhan email
    reset-password-url: ${URL_RESET_PASSWORD:http://localhost:8080/auth/reset-password} #url reset password

azure:
  blob-storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}

jwt:
  expirationMinutes: ${JWT_EXPIRATION_MS:10}
  accessKey: ${JWT_ACCESS_KEY:f0mDtrSt+bRlEszLhbyn97P8a9gRqBHO3/ZR2D5QR0Q=}
  refreshKey: ${JWT_REFRESH_KEY:P2HKzJI3GvYDayyxtX/9x5906PVnrj8aXU8b6RPXjNc=}
  confirmationKey: ${JWT_CONFIRMATION_KEY:Q2HKzJI3GvYDayyxtX/9x5906PVnrj8aXU8b6RPXjNc=}
  resetPasswordKey: ${JWT_RESET_PASSWORD_KEY:cFBkgC3N9GEbKwNope8/ed9kK6Id4oNYAtVIjtcW0mA=}
  expiryDay: ${JWT_EXPIRATION_DAY:14}
  expirationMinutesConfirm: ${JWT_EXPIRATION_MS_CONFIRM:10} #thoi gian ton tai cua token confirm
  expirationMinutesResetPassword: ${JWT_EXPIRATION_MS_RESET_PASSWORD:10} #thoi gian ton tai cua token reset password

repo:
  max-size-gb: ${REPO_MAX_SIZE_GB:10}

