server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
app:
  base-url: ${BASE_URL:http://localhost:8080}
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    azure:
      storage:
        blob:
          container-name: luu-tru-tai-lieu
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: https://luutrutailieukeyvault.vault.azure.net/
              retry:
                mode: exponential
                exponential:
                  max-retries: 4
                  base-delay: PT0.0801S
                  max-delay: PT9S
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/luu-tru-tai-lieu?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 3000
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000 # 1 hour
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 2MB
  mail:
    confirm-url: ${URL_EMAIL_CONFIRMATION:http://localhost:8080/api/v1/user/confirm} #url xac nhan email
    reset-password-url: ${URL_RESET_PASSWORD:http://localhost:8080/auth/reset-password} #url reset password
    invitation-repo-url: ${URL_INVATION:http://localhost:8080/repository/invitation} #url moi thanh vien

azure:
  blob-storage:
    connection-string: ${azurestorageconnectionstring}
    account-name: ${AZURE_STORAGE_CONTAINER_NAME:tathanhmycv}

jwt:
  expirationMinutes: ${JWT_EXPIRATION_MS:100}
  accessKey: ${JWT_ACCESS_KEY:f0mDtrSt+bRlEszLhbyn97P8a9gRqBHO3/ZR2D5QR0Q=}
  refreshKey: ${JWT_REFRESH_KEY:P2HKzJI3GvYDayyxtX/9x5906PVnrj8aXU8b6RPXjNc=}
  confirmationKey: ${JWT_CONFIRMATION_KEY:Q2HKzJI3GvYDayyxtX/9x5906PVnrj8aXU8b6RPXjNc=}
  resetPasswordKey: ${JWT_RESET_PASSWORD_KEY:cFBkgC3N9GEbKwNope8/ed9kK6Id4oNYAtVIjtcW0mA=}
  invitationKey: ${JWT_INVITATION_KEY:Q2HKzJI3GvYDayyxtX/8x5976PVnrj8aXU8b6RPXjNc=}
  expiryDay: ${JWT_EXPIRATION_DAY:14}
  expirationMinutesConfirm: ${JWT_EXPIRATION_MS_CONFIRM:10} #thoi gian ton tai cua token confirm
  expirationMinutesResetPassword: ${JWT_EXPIRATION_MS_RESET_PASSWORD:10} #thoi gian ton tai cua token reset password
  expirationDayInvitation: ${JWT_EXPIRATION_DAY_INVITATION:7} #thoi gian ton tai cua token moi thanh vien

repo:
  max-total-storage-per-user: ${MAX_TOTAL_STORAGE_PER_USER:10737418240} #10GB, được tính bằng tổng dung lượng của tất cả các repo
  max-members-per-repo-default: ${MAX_MEMBER_PER_REPO_DEFAULT:10}
  max-repos-per-member-default: ${MAX_REPOS_PER_MEMBER_DEFAULT:5}

google:
  api-key: ${googleapikey}



