server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    azure:
      storage:
        blob:
          container-name: luu-tru-tai-lieu
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/luu-tru-tai-lieu?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 3000
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 3600000
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 2MB

azure:
  blob-storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}

jwt:
  expirationMinutes: ${JWT_EXPIRATION_MS:1}
  accessKey: ${JWT_ACCESS_KEY:f0mDtrSt+bRlEszLhbyn97P8a9gRqBHO3/ZR2D5QR0Q=}
  refreshKey: ${JWT_REFRESH_KEY:P2HKzJI3GvYDayyxtX/9x5906PVnrj8aXU8b6RPXjNc=}
  expiryDay: ${JWT_EXPIRATION_DAY:14}
